### ISSUE TITLE
Add slider HTML element

### ISSUE THREAD

**Issue by kchang264** [cse112-sp20/team5-project#50]
**Popup.html **
- Create a div under the “my-stats” class element with the class “my-stats-slider”
- Add the necessary elements under this div

**Options.js** 
- Remove updateDomainProductive

**Api.js** 
- Create the function setDomains which takes in a list of domain and updates the users’ doc with them 
- Each element in the parameter domains (a list) should contain the following

> Url (string)
> Productive (boolean, can be null)
> Time (int, can be null)
> Visits (int, can be null)

- First check if the user is logged in, return null if not
- Call the firebase API to retrieve the user’s document
- For each item in domains, check to see if the url is in the pre-existing document.
If it exists, update the values for that domain (ignore the fields that are null). Otherwise, create a new entry for that domain with values specified (0 or true if null)
- Set the updated domains object
- Reference the bottom of incrementDomainVisits for an example

**Comment by madhavMathur** [comment]
Completed
